environment:
    matrix:
    # node.js
    - nodejs_version: "6"

# Install scripts
install:
    # Get latest stable version of node.js
    - ps: Install-Product node $env:nodejs_version
    # Install modules
    - npm install

# Post-install test scripts
test_script:
    # Output useful info for debugging
    - node --version
    - npm --version
    # Run tests
    - npm test

# Don't build
build: off
